# Generated by Django 5.0.7 on 2025-01-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('disability', 'Disability'), ('employment', 'Employment')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='disability',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'disability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disability_choices', to='communityEmpowerment.choice'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'education'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_choices', to='communityEmpowerment.choice'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'employment'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_choices', to='communityEmpowerment.choice'),
        ),
        migrations.DeleteModel(
            name='DisabilityChoice',
        ),
        migrations.DeleteModel(
            name='EducationChoice',
        ),
    ]
