# Generated by Django 5.0.7 on 2025-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
