# Generated by Django 5.0.7 on 2025-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0003_dynamicfield_remove_customuser_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dynamic_field_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
