# Generated by Django 4.2.13 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=36, unique=True)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(max_length=36, unique=True)),
                ('department', models.CharField(default='Unknown', max_length=255)),
                ('scheme_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheme_beneficiary', models.CharField(max_length=255)),
                ('scheme_benefits', models.CharField(max_length=255)),
                ('how_to_avail', models.CharField(max_length=255)),
                ('sponsors', models.CharField(max_length=255)),
                ('age_from', models.CharField(blank=True, max_length=255, null=True)),
                ('age_to', models.CharField(blank=True, max_length=255, null=True)),
                ('funding', models.CharField(max_length=255)),
                ('scheme_link', models.URLField()),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
