# Generated by Django 5.0.6 on 2024-06-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaries', models.CharField(default='Unknown', max_length=255)),
                ('benefits', models.CharField(max_length=255)),
                ('how_to_avail', models.CharField(default='Unknown', max_length=255)),
                ('category', models.CharField(default='Unknown', max_length=255)),
                ('objective', models.CharField(default='Unknown', max_length=255)),
                ('funding_pattern', models.CharField(default='Unknown', max_length=255)),
                ('application_process', models.CharField(default='Unknown', max_length=255)),
                ('contact_office', models.CharField(default='Unknown', max_length=255)),
                ('scheme_link', models.URLField()),
                ('required_documents', models.CharField(default='Unknown', max_length=255)),
                ('other_information', models.CharField(default='Unknown', max_length=255)),
                ('test_info', models.URLField(default='www.google.com')),
                ('scheme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.scheme')),
            ],
        ),
    ]
