# Generated by Django 4.2.13 on 2024-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_scheme_age_from_remove_scheme_age_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('age', models.IntegerField()),
                ('community', models.CharField(max_length=255)),
                ('other_details', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='funding',
            new_name='benefits',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_beneficiary',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_benefits',
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_process',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='beneficiaries',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='contact_office',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='funding_pattern',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='introduced_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheme',
            name='objective',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='other_information',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='required_documents',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='valid_upto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='how_to_avail',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='lower_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_id',
            field=models.CharField(default='Unknown', max_length=360),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='sponsors',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='upper_age',
            field=models.IntegerField(default=0),
        ),
    ]
