# Generated by Django 5.0.6 on 2024-06-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_schemedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemedetail',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='schemedetail',
            name='test_info',
        ),
    ]
