# Generated by Django 4.2.13 on 2024-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_scheme_created_at_scheme_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_id', models.IntegerField()),
                ('sponsor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='sponsors',
        ),
    ]
